### PR TITLE
html and css for the title and navbar

### LINKED ISSUE #29: Developing the webpage title
- [x] create index.html

- [x] A website title for the tab (in the header of the document)

- [x] add the cloud4 Logo

- [x] create navbar

- [x] add link to style.css

### LINKED ISSUE #34: nav bar
- [x] Navigation bar with link of contact info and home page

### PR DESCRIPTION
**Pull request by bringmetheaxx**
I did some stupid stuff so someone check if everything is fine.

### CODE REVIEW

**Comment by danielhalasz** [comment]
yeah, not sure why you changed the h tags, but it works fine :)

**Review by danielhalasz — APPROVED** [review]

**Review by Moamin-AbuEwaida — APPROVED** [review]
Hi @bringmetheaxx everything looks good as I see, but i'm was little bet confused by the commit of index.html with the number "
fa60491 " [the commit in the top] as the file is .html and the content is css code.
then when I reviewed the "Files changed" and found the last changes on the index.html file are the actual code, I think is everything is fine

**Comment by Moamin-AbuEwaida** [comment]
I see @danielhalasz that you reviewed the PR as well :+1:

**Comment by snicoll** [comment]
> yeah, not sure why you changed the h tags, but it works fine :)

Side note (no need to do anything on this particular PR).

Remember that merging a PR is not a race. You can ask a question and wait for the report to give feedback. Then, as a team, you can figure out what's the best solution. To provide contextualized feedback, you can click on the line where the heading was changed and add a comment + "start  review".

**Comment by bringmetheaxx** [comment]
> yeah, not sure why you changed the h tags, but it works fine :)

I actually changed because I created a h1 for the title and you already had a h1, I could use id or class for that, but I was so desperate to finish that it didn't crossed my mind.

**Pull request merged**
