### PR TITLE
Main

### PR DESCRIPTION
**Pull request by seninet**

### CODE REVIEW

**Comment by snicoll** [comment]
@Senait-coding you need to refresh your `main` branch with the latest state of the group's repo and then create a branch for your PR. If you don't do that, you'll keep submitting PRs with commits that are unrelated.

**Comment by seninet** [comment]
> @Senait-coding you need to refresh your `main` branch with the latest state of the group's repo and then create a branch for your PR. If you don't do that, you'll keep submitting PRs with commits that are unrelated.

yes, may be it is not the right way but last time how I updated my fork with the main(origin)  the steps 
I follow were 
 I make comparison (origin main vs my forked main) 
 issue PR 
merge 
got updated fork 
clone to my machine
Do the update
push back to my repo
then issue PR to  the origin ; this  way seems ok for me  but it is not working now the moment I issue PR based on the comparison to do the merge it reaches you and I can't merge and update my fork :(, which way should I have to follow? a bit confused

**Comment by snicoll** [comment]
It isn't the good way. Your `main` must be in the same state as the `origin` main. By issuing a PR, you are changing the history and that leads to problem like this. Also please don't use the GitHub interface for any of that, you should run those commands on your machine. Daniel just shared some info about that.

In your case you'll have to reset your `main` something like:

```
git checkout main
git fetch upstream
git reset upstream/main --hard
```

Note that doing so you'll lose the work in this PR.

**Comment by seninet** [comment]
> It isn't the good way. Your `main` must be in the same state as the `origin` main. By issuing a PR, you are changing the history and that leads to problem like this. Also please don't use the GitHub interface for any of that, you should run those commands on your machine. Daniel just shared some info about that.
> 
> In your case you'll have to reset your `main` something like:
> 
> ```
> git checkout main
> git fetch upstream
> git reset upstream/main --hard
> ```
> 
> Note that doing so you'll lose the work in this PR.

ok, thanks for your explanation and I will try to do it this way, as it worked last time I thought it is the right way to do that

**Comment by danielhalasz** [comment]
and @Senait-coding it looks like there are actually no new changes that you requested to add..the group repo README.md (which is the project description) is already there

**Pull request closed without merging**
