### PR TITLE
Our Project Definition

### PR DESCRIPTION
**Pull request by seninet**

### CODE REVIEW

**Comment by snicoll** [comment]
@Senait-coding before assigning team mates for review, please double check your submission. Ideally you should have done that on your machine already, comparing your `master` branch to this `main`. If you click on "Files changes" above  you'll see a web-view of that. It shows that a number of files have been deleted.

It looks like you created this PR from your `master` branch and it wasn't up to date with the remote.

**Comment by Senait-coding** [comment]
> @Senait-coding before assigning team mates for review, please double check your submission. Ideally you should have done that on your machine already, comparing your `master` branch to this `main`. If you click on "Files changes" above you'll see a web-view of that. It shows that a number of files have been deleted.
> 
> It looks like you created this PR from your `master` branch and it wasn't up to date with the remote.

@snicoll ,thank you for the review, may be it can't be un excuse for my mistakes but yesterday I was telling my group mates i had a problem with my PC and i had to reset it as everything was messed up and finally stacked .  even now i forced it to reset again to its defult status ,as it couldn't recognize and accept me as the owner of the github /  asks me token /   though I put the SSh code and set every  setup. yesterday even I was even given up on everything 😌, because it was changing once master the other time main and so on it confused me  and was trying to fix it almost all the night long 😔. I did the deletion of the images on my github and reload it many times because it couldn't read it and i couldn't let me  back to my machine to fix it. Anyways though it went well in the precourse now seems I got stacked :(. Just tell me if I should give up  and stop from here may be I am not good enough😞

**Comment by snicoll** [comment]
@Senait-coding there is no problem at all. There are a lot of concepts to grasp and it will take time. Please don't give up and let's sync to see how I can help you.

**Comment by iLienstAr** [comment]
@Senait-coding, you're doing great on being perseverant, look for solutions, communicating with your coach @snicoll . This is the right mindset for succeeding at HackYourFuture ;).
You **are** good enough!

**Comment by Moamin-AbuEwaida** [comment]
So in this case should we review this PR and ignore merging it, leave comment and wait for a new PR @snicoll ?

**Comment by danielhalasz** [comment]
> So in this case should we review this PR and ignore merging it, leave comment and wait for a new PR @snicoll ?

I think we can either let Senait figure out the updating&merging/rebasing on her local machine and once she does a push, it will automatically show up here in the same PR..or we could checkout her changes via the CLI, resolve the conflicts and push (as shown in the command line instructions below)..

**Comment by Moamin-AbuEwaida** [comment]
> > So in this case should we review this PR and ignore merging it, leave comment and wait for a new PR @snicoll ?
> 
> I think we can either let Senait figure out the updating&merging/rebasing on her local machine and once she does a push, it will automatically show up here in the same PR..or we could checkout her changes via the CLI, resolve the conflicts and push (as shown in the command line instructions below)..

So when Senait do another PR it will update this one??
in another words we wont end up dealing with 2 PR for the same thing @danielhalasz !

**Comment by danielhalasz** [comment]
she does not have to do a new PR, just push again after making the changes and that should update this PR, as I understand..

**Comment by snicoll** [comment]
You understood perfectly @danielhalasz. 

@Moamin-AbuEwaida a separate PR means a separate issue ID. Anything we would have been discussing/reviewing would be lost and would need to be ported over the new PR. Reviewing a PR means amending it, not creating a new one.

**Comment by danielhalasz** [comment]
thank you @snicoll for showing how to use interactive rebase and other tricks to resolve this issue..I have now created a new PR from your branch

**Pull request closed without merging**
