### PR TITLE
added consultation form

### LINKED ISSUE #32: Consultation
- [x] create form

### PR DESCRIPTION
**Pull request by danielhalasz**

### CODE REVIEW

**Comment by danielhalasz** [comment]
should we do the PRs on new branches of the group repo?

**Review by bringmetheaxx — APPROVED** [review]
everything is ok

**Comment by danielhalasz** [comment]
hm, I didn't know you can merge a commit without having 2 reviews, maybe because you are the repo owner..

**Comment by bringmetheaxx** [comment]
> hm, I didn't know you can merge a commit without having 2 reviews, maybe because you are the repo owner..

I had to change it otherwise we won't be finishing it tomorrow. Now it's requiring only one.

**Pull request merged**
